### ISSUE TITLE
Cover art not loading and high network usage with new album

### ISSUE THREAD

**Issue by chickenedramen** [PKBeam/AMWin-RP#77]
on Apple Music 1.4.4.33, AMWin-RP v1.2.6.3

When listening to a very new album (Lucy - 100% PROD I.V.), the cover art did not load and my bandwidth was being eaten (reaching up to 5+ Mb/s and hovering around 3 Mb/s [rural internet])
[2024-01-22.log](https://github.com/PKBeam/AMWin-RP/files/14006013/2024-01-22.log)

**Comment by zt89** [comment]
Furthermore on cover art not loading, I've noticed that the search for them is case-sensitive, meaning my local files in which I've capitalized words such as "The" in song titles (or even minor differences in artist capitalization) won't find art but those with one-word titles or ones capitalized the exact same way on Apple Music display the art fine.
(also on Apple Music 1.4.4.33, AMWin-RP v1.2.6.3)

**Comment by Trinity086** [comment]
I'm on Apple Music 1.4.4.41 and AMWin-RP v1.4.0 and wanted to add I am also on rural internet with a max of 4mbps down, and AMWin-RP randomly began eating up all my bandwidth and I have no idea why. I haven't changed any setting since I downloaded it. There isn't an update. I have runtime installed. It just decided to start needing all my bandwidth. Having gone through and tweaking every setting, the only fix appears to be unchecking "Scrobble primary artist" for some reason. I have everything else checked except "Check for updates," "RP when music paused," and "Enable ListenBrainz"

**Comment by PKBeam** [comment]
> (reaching up to 5+ Mb/s and hovering around 3 Mb/s [rural internet])
This is probably because it couldn't find any info but kept trying. Our fallback is the Apple Music webpage so this will use a lot more bandwidth compared to something like an API endpoint.

For Apple Music web scraping, the next release will try up to three times to search for song info, and then abandon all searches for the rest of that song. This should cut down network usage by a lot for songs that can't be found.

> Furthermore on cover art not loading, I've noticed that the search for them is case-sensitive

This is by design. Just in case there are two songs with the same name but different capitalisation (rare but possible), requiring the cases to match gives us the best chance of choosing the correct song.
